name: FactionShield
version: ${project.version}
main: ws.billy.FactionShield.FactionShield
author: "BillyDotWS"
website: "https://github.com/MinecraftFreelance/FactionShield"
database: true
description: "FactionShield | made by BillyDotWS"
api-version: 1.19
commands:
  template:
    usage: /<command>
    description: A template command
