name: FactionShield
version: ${project.version}
main: ws.billy.FactionShield.FactionShield
author: "BillyDotWS"
website: "https://github.com/MinecraftFreelance/FactionShield"
description: "FactionShield | made by BillyDotWS"
api-version: 1.18
depend:
  - "Space"
  - "Factions"
